# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-coding-standards 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-coding-standards"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Felix Hawkins", "Peter Hinterseer"]
  s.date = "2015-09-08"
  s.description = "Run check_code to check code against policies"
  s.email = "felix@whimsicaldoodles.com"
  s.executables = ["check_code"]
  s.extra_rdoc_files = [
    "DESCRIPTION.md",
    "GEM.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitattributes",
    ".rubocop.yml",
    ".ruby-gemset",
    ".ruby-version",
    "DESCRIPTION.md",
    "GEM.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "assets/logo.jpg",
    "bin/check_code",
    "config/rails_best_practices.yml",
    "ruby-coding-standards.gemspec",
    "tmp/.gitignore"
  ]
  s.homepage = "http://github.com/theappbusiness/ruby-coding-standards"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Gem to check and apply TAB code policies"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_runtime_dependency(%q<rubocop>, [">= 0"])
      s.add_runtime_dependency(%q<bundler-audit>, [">= 0"])
      s.add_runtime_dependency(%q<brakeman>, [">= 0"])
      s.add_runtime_dependency(%q<rubycritic>, [">= 0"])
      s.add_runtime_dependency(%q<rails_best_practices>, [">= 0"])
      s.add_runtime_dependency(%q<sandi_meter>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rubocop>, [">= 0"])
      s.add_dependency(%q<bundler-audit>, [">= 0"])
      s.add_dependency(%q<brakeman>, [">= 0"])
      s.add_dependency(%q<rubycritic>, [">= 0"])
      s.add_dependency(%q<rails_best_practices>, [">= 0"])
      s.add_dependency(%q<sandi_meter>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rubocop>, [">= 0"])
    s.add_dependency(%q<bundler-audit>, [">= 0"])
    s.add_dependency(%q<brakeman>, [">= 0"])
    s.add_dependency(%q<rubycritic>, [">= 0"])
    s.add_dependency(%q<rails_best_practices>, [">= 0"])
    s.add_dependency(%q<sandi_meter>, [">= 0"])
  end
end

