# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-style-guide 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-style-guide"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.date = "2015-04-29"
  s.description = "Run check_code to check code against policies"
  s.email = "will@theappbusiness.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".gitattributes",
    "CONTRIBUTING.md",
    "README.md",
    "VERSION"
  ]
  s.homepage = "http://github.com/theappbusiness/ruby-style-guide"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Gem to apply TAB code policies"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubocop>, [">= 0"])
      s.add_runtime_dependency(%q<bundler-audit>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<rubocop>, [">= 0"])
      s.add_dependency(%q<bundler-audit>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<rubocop>, [">= 0"])
    s.add_dependency(%q<bundler-audit>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

